CREATE TABLE IF NOT EXISTS organizations
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    api_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying(160) COLLATE pg_catalog."default" NOT NULL,
    created_on timestamp without time zone NOT NULL,
    updated_on timestamp without time zone NOT NULL,
    CONSTRAINT organizations_pkey PRIMARY KEY (id),
    CONSTRAINT organizations_api_id_key UNIQUE (api_id),
    CONSTRAINT organizations_name_key UNIQUE (name)
)

INSERT INTO organizations (
    name,
    created_on,
    updated_on
)
VALUES
(
    'Ball State',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT (name) DO NOTHING;